// Country -> continent table, generated from data/GeoLite2-Country.mmdb by
// looking up an IPv4 sample and recording every distinct
// (country.names.en, continent.names.en) pair - so the names match what
// geoip.c stores byte for byte. Regenerate if a newer GeoLite2 release
// renames a country.
#include "country_continent.h"
#include <stddef.h>
#include <string.h>

static const struct {
    const char *country;
    const char *continent;
} COUNTRY_CONTINENTS[] = {
    { "Afghanistan", "Asia" },
    { "Albania", "Europe" },
    { "Algeria", "Africa" },
    { "American Samoa", "Oceania" },
    { "Andorra", "Europe" },
    { "Angola", "Africa" },
    { "Anguilla", "North America" },
    { "Antarctica", "Antarctica" },
    { "Antigua and Barbuda", "North America" },
    { "Argentina", "South America" },
    { "Armenia", "Asia" },
    { "Aruba", "North America" },
    { "Australia", "Oceania" },
    { "Austria", "Europe" },
    { "Azerbaijan", "Asia" },
    { "Bahamas", "North America" },
    { "Bahrain", "Asia" },
    { "Bangladesh", "Asia" },
    { "Barbados", "North America" },
    { "Belarus", "Europe" },
    { "Belgium", "Europe" },
    { "Belize", "North America" },
    { "Benin", "Africa" },
    { "Bermuda", "North America" },
    { "Bhutan", "Asia" },
    { "Bolivia", "South America" },
    { "Bonaire, Sint Eustatius and Saba", "North America" },
    { "Bosnia and Herzegovina", "Europe" },
    { "Botswana", "Africa" },
    { "Bouvet Island", "Antarctica" },
    { "Brazil", "South America" },
    { "British Indian Ocean Territory", "Asia" },
    { "British Virgin Islands", "North America" },
    { "Brunei", "Asia" },
    { "Bulgaria", "Europe" },
    { "Burkina Faso", "Africa" },
    { "Burundi", "Africa" },
    { "Cabo Verde", "Africa" },
    { "Cambodia", "Asia" },
    { "Cameroon", "Africa" },
    { "Canada", "North America" },
    { "Cayman Islands", "North America" },
    { "Central African Republic", "Africa" },
    { "Chad", "Africa" },
    { "Chile", "South America" },
    { "China", "Asia" },
    { "Colombia", "South America" },
    { "Comoros", "Africa" },
    { "Congo (DRC)", "Africa" },
    { "Congo Republic", "Africa" },
    { "Cook Islands", "Oceania" },
    { "Costa Rica", "North America" },
    { "Croatia", "Europe" },
    { "Cuba", "North America" },
    { "Curaçao", "North America" },
    { "Cyprus", "Europe" },
    { "Czechia", "Europe" },
    { "Denmark", "Europe" },
    { "Djibouti", "Africa" },
    { "Dominica", "North America" },
    { "Dominican Republic", "North America" },
    { "Ecuador", "South America" },
    { "Egypt", "Africa" },
    { "El Salvador", "North America" },
    { "Equatorial Guinea", "Africa" },
    { "Eritrea", "Africa" },
    { "Estonia", "Europe" },
    { "Eswatini", "Africa" },
    { "Ethiopia", "Africa" },
    { "Falkland Islands", "South America" },
    { "Faroe Islands", "Europe" },
    { "Federated States of Micronesia", "Oceania" },
    { "Fiji", "Oceania" },
    { "Finland", "Europe" },
    { "France", "Europe" },
    { "French Guiana", "South America" },
    { "French Polynesia", "Oceania" },
    { "Gabon", "Africa" },
    { "Gambia", "Africa" },
    { "Georgia", "Asia" },
    { "Germany", "Europe" },
    { "Ghana", "Africa" },
    { "Gibraltar", "Europe" },
    { "Greece", "Europe" },
    { "Greenland", "North America" },
    { "Grenada", "North America" },
    { "Guadeloupe", "North America" },
    { "Guam", "Oceania" },
    { "Guatemala", "North America" },
    { "Guernsey", "Europe" },
    { "Guinea", "Africa" },
    { "Guinea-Bissau", "Africa" },
    { "Guyana", "South America" },
    { "Haiti", "North America" },
    { "Honduras", "North America" },
    { "Hong Kong", "Asia" },
    { "Hungary", "Europe" },
    { "Iceland", "Europe" },
    { "India", "Asia" },
    { "Indonesia", "Asia" },
    { "Iran", "Asia" },
    { "Iraq", "Asia" },
    { "Ireland", "Europe" },
    { "Isle of Man", "Europe" },
    { "Israel", "Asia" },
    { "Italy", "Europe" },
    { "Ivory Coast", "Africa" },
    { "Jamaica", "North America" },
    { "Japan", "Asia" },
    { "Jersey", "Europe" },
    { "Jordan", "Asia" },
    { "Kazakhstan", "Asia" },
    { "Kenya", "Africa" },
    { "Kiribati", "Oceania" },
    { "Kosovo", "Europe" },
    { "Kuwait", "Asia" },
    { "Kyrgyzstan", "Asia" },
    { "Laos", "Asia" },
    { "Latvia", "Europe" },
    { "Lebanon", "Asia" },
    { "Lesotho", "Africa" },
    { "Liberia", "Africa" },
    { "Libya", "Africa" },
    { "Liechtenstein", "Europe" },
    { "Lithuania", "Europe" },
    { "Luxembourg", "Europe" },
    { "Macao", "Asia" },
    { "Madagascar", "Africa" },
    { "Malawi", "Africa" },
    { "Malaysia", "Asia" },
    { "Maldives", "Asia" },
    { "Mali", "Africa" },
    { "Malta", "Europe" },
    { "Marshall Islands", "Oceania" },
    { "Martinique", "North America" },
    { "Mauritania", "Africa" },
    { "Mauritius", "Africa" },
    { "Mayotte", "Africa" },
    { "Mexico", "North America" },
    { "Moldova", "Europe" },
    { "Monaco", "Europe" },
    { "Mongolia", "Asia" },
    { "Montenegro", "Europe" },
    { "Montserrat", "North America" },
    { "Morocco", "Africa" },
    { "Mozambique", "Africa" },
    { "Myanmar", "Asia" },
    { "Namibia", "Africa" },
    { "Nauru", "Oceania" },
    { "Nepal", "Asia" },
    { "New Caledonia", "Oceania" },
    { "New Zealand", "Oceania" },
    { "Nicaragua", "North America" },
    { "Niger", "Africa" },
    { "Nigeria", "Africa" },
    { "Niue", "Oceania" },
    { "Norfolk Island", "Oceania" },
    { "North Korea", "Asia" },
    { "North Macedonia", "Europe" },
    { "Northern Mariana Islands", "Oceania" },
    { "Norway", "Europe" },
    { "Oman", "Asia" },
    { "Pakistan", "Asia" },
    { "Palau", "Oceania" },
    { "Palestine", "Asia" },
    { "Panama", "North America" },
    { "Papua New Guinea", "Oceania" },
    { "Paraguay", "South America" },
    { "Peru", "South America" },
    { "Philippines", "Asia" },
    { "Pitcairn Islands", "Oceania" },
    { "Poland", "Europe" },
    { "Portugal", "Europe" },
    { "Puerto Rico", "North America" },
    { "Qatar", "Asia" },
    { "Romania", "Europe" },
    { "Russia", "Europe" },
    { "Rwanda", "Africa" },
    { "Réunion", "Africa" },
    { "Saint Barthélemy", "North America" },
    { "Saint Kitts and Nevis", "North America" },
    { "Saint Lucia", "North America" },
    { "Saint Martin", "North America" },
    { "Saint Pierre and Miquelon", "North America" },
    { "Saint Vincent and the Grenadines", "North America" },
    { "Samoa", "Oceania" },
    { "San Marino", "Europe" },
    { "Saudi Arabia", "Asia" },
    { "Senegal", "Africa" },
    { "Serbia", "Europe" },
    { "Seychelles", "Africa" },
    { "Sierra Leone", "Africa" },
    { "Singapore", "Asia" },
    { "Sint Maarten", "North America" },
    { "Slovakia", "Europe" },
    { "Slovenia", "Europe" },
    { "Solomon Islands", "Oceania" },
    { "Somalia", "Africa" },
    { "South Africa", "Africa" },
    { "South Georgia and the South Sandwich Islands", "Antarctica" },
    { "South Korea", "Asia" },
    { "South Sudan", "Africa" },
    { "Spain", "Europe" },
    { "Sri Lanka", "Asia" },
    { "St. Helena", "Africa" },
    { "Sudan", "Africa" },
    { "Suriname", "South America" },
    { "Svalbard and Jan Mayen", "Europe" },
    { "Sweden", "Europe" },
    { "Switzerland", "Europe" },
    { "Syria", "Asia" },
    { "São Tomé and Príncipe", "Africa" },
    { "Taiwan", "Asia" },
    { "Tajikistan", "Asia" },
    { "Tanzania", "Africa" },
    { "Thailand", "Asia" },
    { "The Netherlands", "Europe" },
    { "Timor-Leste", "Oceania" },
    { "Togo", "Africa" },
    { "Tokelau", "Oceania" },
    { "Tonga", "Oceania" },
    { "Trinidad and Tobago", "North America" },
    { "Tunisia", "Africa" },
    { "Turkmenistan", "Asia" },
    { "Turks and Caicos Islands", "North America" },
    { "Tuvalu", "Oceania" },
    { "Türkiye", "Asia" },
    { "U.S. Virgin Islands", "North America" },
    { "Uganda", "Africa" },
    { "Ukraine", "Europe" },
    { "United Arab Emirates", "Asia" },
    { "United Kingdom", "Europe" },
    { "United States", "North America" },
    { "United States Minor Outlying Islands", "Oceania" },
    { "Uruguay", "South America" },
    { "Uzbekistan", "Asia" },
    { "Vanuatu", "Oceania" },
    { "Vatican City", "Europe" },
    { "Venezuela", "South America" },
    { "Vietnam", "Asia" },
    { "Wallis and Futuna", "Oceania" },
    { "Yemen", "Asia" },
    { "Zambia", "Africa" },
    { "Zimbabwe", "Africa" },
    { "Åland Islands", "Europe" },
};

const char *country_continent(const char *country) {
    if (!country) return NULL;
    for (size_t i = 0; i < sizeof(COUNTRY_CONTINENTS) / sizeof(COUNTRY_CONTINENTS[0]); i++)
        if (strcmp(COUNTRY_CONTINENTS[i].country, country) == 0) return COUNTRY_CONTINENTS[i].continent;
    return NULL;
}
